version: '2'

networks:
  test-net:
    external: true

services:
  cli.test.com:
    container_name: cli.test.com
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      # - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.test.com
      - CORE_PEER_ADDRESS=peer0.test.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peerOrganizations/test.com/peers/peer0.test.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peerOrganizations/test.com/peers/peer0.test.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/test.com/peers/peer0.test.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/test.com/users/Admin@test.com/msp
    working_dir: /etc/hyperledger
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./cli/scripts:/etc/hyperledger/scripts/
        - ../crypto-config:/etc/hyperledger/crypto/
        - ../channel-artifacts:/etc/hyperledger/channel-artifacts
    networks:
      - test-net
