version: "2"

networks:
  test-net:
    external: true

services:
  nginx.test.com:
    image: nginx
    container_name: nginx.test.com
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      # - 80:80
      # - 443:443
      - 8000:80
      - 4430:443
    networks:
      - test-net