version: '2'

volumes:
  peer1.test.com:
  couchdb1.test.com:

networks:
  test-net:
    external: true

services:
  couchdb1.test.com:
    container_name: couchdb1.test.com
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - couchdb1.test.com:/opt/couchdb/data
    ports:
      - 6984:5984
    networks:
      - test-net

  peer1.test.com:
    image: hyperledger/fabric-peer:1.4.4
    # image: hyperledger/fabric-peer:$IMAGE_TAG
    container_name: peer1.test.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ID=peer1.test.com
      - CORE_PEER_ADDRESS=peer1.test.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.test.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Gossip
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.test.com:8051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.test.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/test.com/peers/peer1.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/test.com/peers/peer1.test.com/tls:/etc/hyperledger/fabric/tls
        - peer1.test.com:/var/hyperledger/production
    depends_on:
      - couchdb1.test.com
    ports:
      - 8051:8051
    networks:
      - test-net
