OrdererOrgs:
  - Name: Orderer
    Domain: test.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

PeerOrgs:
  - Name: Org1
    Domain: test.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
