version: "2"

volumes:
  ca.test.com:

networks:
  test-net:
    external: true

services:
  ca.test.com:
    container_name: ca.test.com
    image: hyperledger/fabric-ca:1.4.4
    restart: always
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.test.com
      # Cert
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.crt
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/ca.key
      # TLS
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/ca/ca.crt
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/ca/ca.key
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_REGISTRY_MAXENROLLMENTS=-1
      # CSR
      - FABRIC_CA_SERVER_CSR_CN=ca.test.com
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.test.com
    ports:
      - 7054:7054
    volumes:
      - ../crypto-config/peerOrganizations/test.com/ca/:/etc/hyperledger/ca
      - ./ca/scripts/:/etc/hyperledger/scripts
      - ca.test.com:/etc/hyperledger/fabric-ca-server
    working_dir: /etc/hyperledger/fabric-ca-server
    command: /bin/bash -c 'fabric-ca-server start -b admin:adminpw --cfg.affiliations.allowremove'
    networks:
      - test-net
