version: '2'

volumes:
  peer0.org2.com:
  couchdb0.org2.com:

networks:
  test-net:
    external: true

services:

  couchdb0.org2.com:
    container_name: couchdb0.org2.com
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - couchdb0.org2.com:/opt/couchdb/data
    ports:
      - 7984:5984
    networks:
      - test-net
  
  peer0.org2.com:
    image: hyperledger/fabric-peer:1.4.4
    # image: hyperledger/fabric-peer:$IMAGE_TAG
    container_name: peer0.org2.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ID=peer0.org2.com
      - CORE_PEER_ADDRESS=peer0.org2.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Gossip
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.com:8051 # Remark because no org2
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.com:11051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # CouchDB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org2.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.com:/var/hyperledger/production
    depends_on:
      - couchdb0.org2.com
    ports:
      - 11051:7051
    networks:
      - test-net

  cli.org2.com:
    container_name: cli.org2.com
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      # - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli.org2.com
      - CORE_PEER_ADDRESS=peer0.org2.com:11051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peerOrganizations/org2.com/peers/peer0.org2.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peerOrganizations/org2.com/peers/peer0.org2.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peerOrganizations/org2.com/peers/peer0.org2.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/org2.com/users/Admin@org2.com/msp
    working_dir: /etc/hyperledger
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./sacc/:/opt/gopath/src/github.com/chaincode/sacc
        # - ./cli/scripts:/etc/hyperledger/scripts/
        - ./crypto-config:/etc/hyperledger/crypto/
        # - ../channel-artifacts:/etc/hyperledger/channel-artifacts
    networks:
      - test-net
